# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ConsumptionService:
        public: true

    App\DAL\Writer\Doctrine\ToyCarWriter:
        public: true

    App\DAL\Reader\Doctrine\ColorReader:
        public: true

    App\DAL\Reader\Doctrine\ManufacturerReader:
        public: true

    App\DAL\Reader\Doctrine\ToyCarReader:
        public: true

    App\Factory\ToyCarValidatorFactory:
        public: true

    App\Validator\ToyCarValidator:
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
